apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: example-app
      replicas: two
  template:
    metadata:
      labels:
        app: example-app
    spec:
       containers:
         - name: example-app
           image: argoproj/argocd:v2.6.15
           ports:
           - containerPort: 8080